# Generated by Django 5.1.6 on 2025-07-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название евента для пользователя')),
                ('chanel_name', models.CharField(max_length=50, verbose_name='Название кнала с собачкой')),
                ('price', models.IntegerField(default=1000, verbose_name='Выплата юзеру за подписку')),
                ('remaining_number_of_clicks', models.IntegerField(default=1, verbose_name='Максимально возможное количество переходов по ссылке')),
                ('users', models.JSONField(blank=True, default=list, verbose_name='Пользователи перешедшие по ссылке')),
            ],
            options={
                'verbose_name': 'Евент',
                'verbose_name_plural': 'Евенты',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('goods_price', models.IntegerField(default=1000, verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_tg_name', models.CharField(blank=True, default='none', max_length=35, null=True, verbose_name='Имя аккаунта в телеграм')),
                ('user_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Имя')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Активна ли подписка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
